dist: trusty
sudo: required
services:
  - docker

language: node_js
node_js:
# [- Your NodeJS version]
- '7'

branches:
  only:
  # - Your branch name
    - rk3


script:
- export REGISTRY=registry.heroku.com
- docker login --username=_ --password=$(echo $API_KEY) $REGISTRY
- docker build -t $REGISTRY/$APP_NAME/web .
- docker push $REGISTRY/$APP_NAME/web
